apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster
  region: ap-south-1   # change if needed

iam:
  withOIDC: true

vpc:
  cidr: 10.0.0.0/18
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  nat:
    gateway: Single

managedNodeGroups:
  - name: nodes
    instanceType: t3.small
    spot: true
    minSize: 2
    maxSize: 5
    desiredCapacity: 5
    volumeSize: 20
    ssh:
      allow: true
      publicKeyName: t3  
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        efs: true
        albIngress: true
    labels:
      nodegroup-type: managed
    tags:
      nodegroup-role: worker

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy
  - name: aws-ebs-csi-driver
